# Generated by Django 4.2.7 on 2023-12-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
