# Generated by Django 4.2.7 on 2023-11-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='files/profile/default.jpg', upload_to='files/profile/'),
        ),
    ]
